// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMbszarMjN16YIbSRJ8na0vIudUM2wQns',
    appId: '1:875427486294:android:4b72d259e7e52468abf9f7',
    messagingSenderId: '875427486294',
    projectId: 'appmyjuice',
    storageBucket: 'appmyjuice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdsjcksqC9yFZewKVMxNljNfnoH_dsNpc',
    appId: '1:875427486294:ios:66913915ba24c86babf9f7',
    messagingSenderId: '875427486294',
    projectId: 'appmyjuice',
    storageBucket: 'appmyjuice.appspot.com',
    iosBundleId: 'com.example.appmyjuice',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMbszarMjN16YIbSRJ8na0vIudUM2wQns',
    appId: '1:875427486294:android:4b72d259e7e52468abf9f7',
    messagingSenderId: '875427486294',
    projectId: 'appmyjuice',
    storageBucket: 'appmyjuice.appspot.com',
  );
}
